# Generated by Django 5.2.7 on 2025-10-21 10:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='intensity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='issue_type',
            field=models.CharField(choices=[('garbage', 'Garbage'), ('pothole', 'Pothole'), ('waterlogging', 'Waterlogging'), ('street_light', 'Broken Streetlight'), ('accident', 'Road Accident Zone'), ('crime', 'Crime Hotspot'), ('other', 'Other')], default='other', max_length=50, verbose_name='Type of Issue'),
        ),
    ]
