# Generated by Django 5.2.7 on 2025-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_issuereport_intensity_alter_issuereport_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='issue_type',
            field=models.CharField(choices=[('garbage', 'Garbage'), ('pothole', 'Pothole'), ('waterlogging', 'Waterlogging'), ('electricity_issue', 'Electricity Issue'), ('stray_animal', 'Stray Animal'), ('other', 'Other')], default='other', max_length=50, verbose_name='Type of Issue'),
        ),
    ]
